"use client";

import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "../../queryClient";

// Sonner
import { Toaster, toast } from "sonner";

import "react-confirm-alert/src/react-confirm-alert.css";

// import "react-spring-bottom-sheet/dist/style.css";
// import "react-spring-bottom-sheet/dist/style.css";

import localFont from "next/font/local";
import "./globals.css";
import "@uploadthing/react/styles.css";

// Components
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useEffect, useLayoutEffect } from "react";
import { useRefreshToken, useRequestsUsers } from "./hooks/request/users/requestsUsers";
import Head from "next/head";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// useLayoutEffect(() => {
//     console.log("first render");
// }, []);

export default function RootLayout({ children }) {
    const { useGetUserInformation } = useRequestsUsers();

    useLayoutEffect(() => {
        useGetUserInformation();
        // useRefreshToken();
    }, []);

    return (
        <html lang="en">
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=0.8" />
            </Head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased width mb-24 bg-gray-100`}>
                <Toaster />
                <QueryClientProvider client={queryClient}>
                    <Header />
                    {children}
                    <Footer />
                </QueryClientProvider>
            </body>
        </html>
    );
}
